[package]
name = "examples"
version = "0.0.0"
edition = "2021"
publish = false
authors = ["Alejandro Palomino <alejandropalomino22@gmail.com>"]

[[example]]
name = "client"
path = "client.rs"

[dev-dependencies]
websocket-std = { version = "0.0.2", path = "../websocket" }